apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: muchtodo
data:
  ".env": |
    PORT=8080
    MONGO_URI=mongodb://mongodb-service.muchtodo.svc.cluster.local:27017
    DB_NAME=much_todo_db
    JWT_EXPIRATION_HOURS="72"
    LOG_LEVEL=DEBUG
    LOG_FORMAT="json"
    INTEGRATION="true"
