apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
data:
  mongo-username: bXVjaF90b2RvX3VzZXI=
  mongo-password: TW9nZGJEMGMxMjM=
  jwt-secret-key: aUNWZDdxdmRLSTg0RHd1M3o1dVVhaElxMnVCcUlvalRTMmpROGdGUFB6T0UzWFNzRVBmQmZaY0w2SFNwTTNPeFR2eVdyQTRTSHAyUDRSS3cyNU5MNTc2ZlU0djFaeUxXeEQ0UlBhZlZ3QTJwdnhIdGlKWERzdHlSbERxZk5oN3A=
